name: institute_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  badges: ^2.0.3
  cupertino_icons: ^1.0.2
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.2.5
  flutter_svg: ^1.1.6
  http: ^0.13.5
  image_picker: ^0.8.6
  intl: ^0.18.0
  path_provider: ^2.0.11
  provider: ^6.0.5
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/icons/
    - assets/images/
    - assets/temp/
    - assets/illustrations/
    - assets/background/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
